In [36]:
!git clone https://github.com/arantafall/housing_BCN.git

Cloning into 'housing_BCN'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 40 (delta 15), reused 32 (delta 8), pack-reused 0 (from 0)
Receiving objects: 100% (40/40), 338.30 KiB | 5.46 MiB/s, done.
Resolving deltas: 100% (15/15), done.

In [37]:
cd housing_BCN

/content/housing_BCN/housing_BCN

In [38]:
cat dataframe.ipynb

cat: dataframe.ipynb: No such file or directory

In [39]:
import pandas as pd
import numpy as np

In [40]:
data = pd.read_csv("data/Barcelona_Fotocasa_HousingPrices.csv")

In [41]:
!git config --global user.name Arantafall
!git config --global user.email aran.tafall.campusimpelia@gmail.com

In [42]:
data.shape

(8188, 10)

In [43]:
data.head()

,Unnamed: 0,price,rooms,bathroom,lift,terrace,square_meters,real_state,neighborhood,square_meters_price
0,0,750,3,1,True,False,60,flat,Horta- Guinardo,12.500000
1,1,770,2,1,True,False,59,flat,Sant Andreu,13.050847
2,2,1300,1,1,True,True,30,flat,Gràcia,43.333333
3,3,2800,1,1,True,True,70,flat,Ciutat Vella,40.000000
4,4,720,2,1,True,False,44,flat,Sant Andreu,16.363636

In [44]:
!git checkout -b aran

Switched to a new branch 'aran'

In [45]:
!git branch

* aran
  main

In [46]:
data.isnull().sum()
(data.isnull().sum() / len(data)) * 100

Unnamed: 0             0.000000
price                  0.000000
rooms                  0.000000
bathroom               0.000000
lift                   0.000000
terrace                0.000000
square_meters          0.000000
real_state             3.273083
neighborhood           0.000000
square_meters_price    0.000000
dtype: float64

In [47]:
data.describe().round(2)

,Unnamed: 0,price,rooms,bathroom,square_meters,square_meters_price
count,8188.00,8188.00,8188.00,8188.00,8188.00,8188.00
mean,4093.50,1444.09,2.42,1.51,84.61,17.74
std,2363.82,1125.89,1.14,0.73,47.87,9.25
min,0.00,320.00,0.00,1.00,10.00,4.91
25%,2046.75,875.00,2.00,1.00,56.00,12.79
50%,4093.50,1100.00,2.00,1.00,73.00,15.31
75%,6140.25,1540.00,3.00,2.00,95.00,19.44
max,8187.00,15000.00,10.00,8.00,679.00,186.67

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8188 entries, 0 to 8187
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           8188 non-null   int64
 1   price                8188 non-null   int64
 2   rooms                8188 non-null   int64
 3   bathroom             8188 non-null   int64
 4   lift                 8188 non-null   bool
 5   terrace              8188 non-null   bool
 6   square_meters        8188 non-null   int64
 7   real_state           7920 non-null   object
 8   neighborhood         8188 non-null   object
 9   square_meters_price  8188 non-null   float64
dtypes: bool(2), float64(1), int64(5), object(2)
memory usage: 527.9+ KB

In [49]:
data.rename(columns={'real_state': 'property_type'}, inplace=True)

In [50]:
data['property_type'].unique()

array(['flat', 'attic', nan, 'apartment', 'study'], dtype=object)

In [51]:
data

,Unnamed: 0,price,rooms,bathroom,lift,terrace,square_meters,property_type,neighborhood,square_meters_price
0,0,750,3,1,True,False,60,flat,Horta- Guinardo,12.500000
1,1,770,2,1,True,False,59,flat,Sant Andreu,13.050847
2,2,1300,1,1,True,True,30,flat,Gràcia,43.333333
3,3,2800,1,1,True,True,70,flat,Ciutat Vella,40.000000
4,4,720,2,1,True,False,44,flat,Sant Andreu,16.363636
...,...,...,...,...,...,...,...,...,...,...
8183,8183,1075,2,2,False,False,65,flat,Gràcia,16.538462
8184,8184,1500,3,2,True,False,110,flat,Eixample,13.636364
8185,8185,1500,2,2,True,True,90,flat,Sarria-Sant Gervasi,16.666667
8186,8186,1500,3,2,True,False,110,flat,Eixample,13.636364
8187,8187,1500,3,2,True,False,110,flat,Eixample,13.636364

In [52]:
print(data['property_type'].unique())
print(data['property_type'].dtype)

['flat' 'attic' nan 'apartment' 'study']
object

In [53]:
data['property_type'].value_counts()

property_type
flat         6505
apartment     991
attic         315
study         109
Name: count, dtype: int64

In [54]:
data = data.dropna(subset=['property_type'])
data.reset_index(drop=True, inplace=True)

In [55]:
data

,Unnamed: 0,price,rooms,bathroom,lift,terrace,square_meters,property_type,neighborhood,square_meters_price
0,0,750,3,1,True,False,60,flat,Horta- Guinardo,12.500000
1,1,770,2,1,True,False,59,flat,Sant Andreu,13.050847
2,2,1300,1,1,True,True,30,flat,Gràcia,43.333333
3,3,2800,1,1,True,True,70,flat,Ciutat Vella,40.000000
4,4,720,2,1,True,False,44,flat,Sant Andreu,16.363636
...,...,...,...,...,...,...,...,...,...,...
7915,8183,1075,2,2,False,False,65,flat,Gràcia,16.538462
7916,8184,1500,3,2,True,False,110,flat,Eixample,13.636364
7917,8185,1500,2,2,True,True,90,flat,Sarria-Sant Gervasi,16.666667
7918,8186,1500,3,2,True,False,110,flat,Eixample,13.636364
7919,8187,1500,3,2,True,False,110,flat,Eixample,13.636364

In [56]:
!git add .

In [57]:
!git commit -m 'las filas con valor nulo en la columna real_state fueron eliminadas y cambio de nombre de esta columna a property_type'

On branch aran
nothing to commit, working tree clean

In [58]:
!git checkout main

Switched to branch 'main'
Your branch is up to date with 'origin/main'.

In [59]:
!git pull origin main

From https://github.com/arantafall/housing_BCN
 * branch            main       -> FETCH_HEAD
Already up to date.

In [60]:
!git merge aran

Already up to date.

In [61]:
!git push https://Arantafall:@github.com/Arantafall/https://github.com/arantafall/housing_BCN.git/

remote: Not Found
fatal: repository 'https://github.com/Arantafall/https://github.com/arantafall/housing_BCN.git/' not found

In [62]:
!git push https://Arantafall:@github.com/Arantafall/housing_BCN.git

remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Arantafall/housing_BCN.git/'

In [63]:
data.head()

,Unnamed: 0,price,rooms,bathroom,lift,terrace,square_meters,property_type,neighborhood,square_meters_price
0,0,750,3,1,True,False,60,flat,Horta- Guinardo,12.500000
1,1,770,2,1,True,False,59,flat,Sant Andreu,13.050847
2,2,1300,1,1,True,True,30,flat,Gràcia,43.333333
3,3,2800,1,1,True,True,70,flat,Ciutat Vella,40.000000
4,4,720,2,1,True,False,44,flat,Sant Andreu,16.363636

In [64]:
data.describe()

,Unnamed: 0,price,rooms,bathroom,square_meters,square_meters_price
count,7920.000000,7920.000000,7920.000000,7920.000000,7920.000000,7920.000000
mean,4102.152399,1434.894949,2.444066,1.504672,84.538636,17.625957
std,2362.481061,1119.528321,1.125266,0.728770,47.584487,9.015493
min,0.000000,320.000000,0.000000,1.000000,10.000000,5.555556
25%,2052.750000,875.000000,2.000000,1.000000,56.000000,12.777778
50%,4098.500000,1100.000000,2.000000,1.000000,73.000000,15.217391
75%,6155.250000,1500.000000,3.000000,2.000000,95.000000,19.298246
max,8187.000000,15000.000000,10.000000,8.000000,679.000000,185.000000

In [65]:
data["price"].describe()

count     7920.000000
mean      1434.894949
std       1119.528321
min        320.000000
25%        875.000000
50%       1100.000000
75%       1500.000000
max      15000.000000
Name: price, dtype: float64

In [66]:
 data["square_meters"].describe()

count    7920.000000
mean       84.538636
std        47.584487
min        10.000000
25%        56.000000
50%        73.000000
75%        95.000000
max       679.000000
Name: square_meters, dtype: float64

In [67]:
data["rooms"].describe()

count    7920.000000
mean        2.444066
std         1.125266
min         0.000000
25%         2.000000
50%         2.000000
75%         3.000000
max        10.000000
Name: rooms, dtype: float64

In [68]:
data.head()

,Unnamed: 0,price,rooms,bathroom,lift,terrace,square_meters,property_type,neighborhood,square_meters_price
0,0,750,3,1,True,False,60,flat,Horta- Guinardo,12.500000
1,1,770,2,1,True,False,59,flat,Sant Andreu,13.050847
2,2,1300,1,1,True,True,30,flat,Gràcia,43.333333
3,3,2800,1,1,True,True,70,flat,Ciutat Vella,40.000000
4,4,720,2,1,True,False,44,flat,Sant Andreu,16.363636

In [69]:
data[["neighborhood","square_meters"]].describe()

       square_meters
count    7920.000000
mean       84.538636
std        47.584487
min        10.000000
25%        56.000000
50%        73.000000
75%        95.000000
max       679.000000

In [70]:
data.terrace.describe()

count      7920
unique        2
top       False
freq       6294
Name: terrace, dtype: object

In [71]:
data.terrace.value_counts()

terrace
False    6294
True     1626
Name: count, dtype: int64

In [72]:
print(data[['square_meters_price', 'neighborhood']].describe())

       square_meters_price
count          7920.000000
mean             17.625957
std               9.015493
min               5.555556
25%              12.777778
50%              15.217391
75%              19.298246
max             185.000000

In [73]:
print(data['neighborhood'].value_counts())

neighborhood
Eixample               2360
Sarria-Sant Gervasi    1320
Ciutat Vella           1314
Gràcia                  658
Sant Martí              592
Sants-Montjuïc          572
Les Corts               512
Horta- Guinardo         305
Sant Andreu             174
Nou Barris              113
Name: count, dtype: int64

In [74]:
data['square_meters_price'].describe();
data['neighborhood'].describe()

count         7920
unique          10
top       Eixample
freq          2360
Name: neighborhood, dtype: object

In [75]:
data.head()

,Unnamed: 0,price,rooms,bathroom,lift,terrace,square_meters,property_type,neighborhood,square_meters_price
0,0,750,3,1,True,False,60,flat,Horta- Guinardo,12.500000
1,1,770,2,1,True,False,59,flat,Sant Andreu,13.050847
2,2,1300,1,1,True,True,30,flat,Gràcia,43.333333
3,3,2800,1,1,True,True,70,flat,Ciutat Vella,40.000000
4,4,720,2,1,True,False,44,flat,Sant Andreu,16.363636

In [76]:
data['square_meters_price'] > 1000

0       False
1       False
2       False
3       False
4       False
        ...
7915    False
7916    False
7917    False
7918    False
7919    False
Name: square_meters_price, Length: 7920, dtype: bool

In [77]:
#Precio por metro cuadrado depeniendo del barrio
grouped_stats = data.groupby('neighborhood')['square_meters_price'].mean()
(grouped_stats)

neighborhood
Ciutat Vella           19.032033
Eixample               18.943313
Gràcia                 16.897971
Horta- Guinardo        13.564087
Les Corts              15.806625
Nou Barris             12.440466
Sant Andreu            13.146563
Sant Martí             17.833465
Sants-Montjuïc         16.443467
Sarria-Sant Gervasi    17.331831
Name: square_meters_price, dtype: float64

In [78]:
#Precio por m2 dependiendo del  barrio
price_stats = data.groupby('neighborhood')['square_meters_price'].agg(['mean', 'min', 'max', 'median']).round(2)
(price_stats)

                      mean   min     max  median
neighborhood
Ciutat Vella         19.03  6.57  185.00   17.00
Eixample             18.94  6.74  144.50   15.59
Gràcia               16.90  7.00   92.50   14.62
Horta- Guinardo      13.56  7.16   37.67   12.73
Les Corts            15.81  8.12   47.06   14.71
Nou Barris           12.44  8.77   25.38   12.50
Sant Andreu          13.15  7.00   42.86   12.50
Sant Martí           17.83  8.09   75.36   15.23
Sants-Montjuïc       16.44  8.62  100.00   14.21
Sarria-Sant Gervasi  17.33  5.56   48.43   15.92

In [79]:
data.head()

,Unnamed: 0,price,rooms,bathroom,lift,terrace,square_meters,property_type,neighborhood,square_meters_price
0,0,750,3,1,True,False,60,flat,Horta- Guinardo,12.500000
1,1,770,2,1,True,False,59,flat,Sant Andreu,13.050847
2,2,1300,1,1,True,True,30,flat,Gràcia,43.333333
3,3,2800,1,1,True,True,70,flat,Ciutat Vella,40.000000
4,4,720,2,1,True,False,44,flat,Sant Andreu,16.363636

In [84]:
price_per_room = data.groupby('rooms')['square_meters_price'].mean().round(2)
(price_per_room)

rooms
0     18.34
1     21.71
2     18.43
3     15.65
4     14.72
5     15.54
6     14.90
7     10.95
9     10.13
10    18.42
Name: square_meters_price, dtype: float64