<a href="https://colab.research.google.com/github/arantafall/housing_BCN/blob/main/Untitled10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
!git clone https://github.com/arantafall/housing_BCN.git

Cloning into 'housing_BCN'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 13 (delta 1), reused 12 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (13/13), 104.49 KiB | 786.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.

In [16]:
cd housing_BCN

/content/housing_BCN/housing_BCN

In [17]:
cat dataframe.ipynb

cat: dataframe.ipynb: No such file or directory

In [18]:
import pandas as pd
import numpy as np

In [19]:
data = pd.read_csv("data/Barcelona_Fotocasa_HousingPrices.csv")

In [20]:
!git config --global user.name Arantafall
!git config --global user.email aran.tafall.campusimpelia@gmail.com

In [21]:
data.shape

(8188, 10)

In [22]:
data.head()

,Unnamed: 0,price,rooms,bathroom,lift,terrace,square_meters,real_state,neighborhood,square_meters_price
0,0,750,3,1,True,False,60,flat,Horta- Guinardo,12.500000
1,1,770,2,1,True,False,59,flat,Sant Andreu,13.050847
2,2,1300,1,1,True,True,30,flat,Gràcia,43.333333
3,3,2800,1,1,True,True,70,flat,Ciutat Vella,40.000000
4,4,720,2,1,True,False,44,flat,Sant Andreu,16.363636

In [23]:
!git checkout -b aran

Switched to a new branch 'aran'

In [24]:
!git branch

* aran
  main

In [25]:
data.isnull().sum()
(data.isnull().sum() / len(data)) * 100

Unnamed: 0             0.000000
price                  0.000000
rooms                  0.000000
bathroom               0.000000
lift                   0.000000
terrace                0.000000
square_meters          0.000000
real_state             3.273083
neighborhood           0.000000
square_meters_price    0.000000
dtype: float64

In [26]:
data.describe().round(2)

,Unnamed: 0,price,rooms,bathroom,square_meters,square_meters_price
count,8188.00,8188.00,8188.00,8188.00,8188.00,8188.00
mean,4093.50,1444.09,2.42,1.51,84.61,17.74
std,2363.82,1125.89,1.14,0.73,47.87,9.25
min,0.00,320.00,0.00,1.00,10.00,4.91
25%,2046.75,875.00,2.00,1.00,56.00,12.79
50%,4093.50,1100.00,2.00,1.00,73.00,15.31
75%,6140.25,1540.00,3.00,2.00,95.00,19.44
max,8187.00,15000.00,10.00,8.00,679.00,186.67

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8188 entries, 0 to 8187
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           8188 non-null   int64
 1   price                8188 non-null   int64
 2   rooms                8188 non-null   int64
 3   bathroom             8188 non-null   int64
 4   lift                 8188 non-null   bool
 5   terrace              8188 non-null   bool
 6   square_meters        8188 non-null   int64
 7   real_state           7920 non-null   object
 8   neighborhood         8188 non-null   object
 9   square_meters_price  8188 non-null   float64
dtypes: bool(2), float64(1), int64(5), object(2)
memory usage: 527.9+ KB

In [30]:
data['property_type'].unique()

array(['flat', 'attic', nan, 'apartment', 'study'], dtype=object)

In [31]:
data

,Unnamed: 0,price,rooms,bathroom,lift,terrace,square_meters,property_type,neighborhood,square_meters_price
0,0,750,3,1,True,False,60,flat,Horta- Guinardo,12.500000
1,1,770,2,1,True,False,59,flat,Sant Andreu,13.050847
2,2,1300,1,1,True,True,30,flat,Gràcia,43.333333
3,3,2800,1,1,True,True,70,flat,Ciutat Vella,40.000000
4,4,720,2,1,True,False,44,flat,Sant Andreu,16.363636
...,...,...,...,...,...,...,...,...,...,...
8183,8183,1075,2,2,False,False,65,flat,Gràcia,16.538462
8184,8184,1500,3,2,True,False,110,flat,Eixample,13.636364
8185,8185,1500,2,2,True,True,90,flat,Sarria-Sant Gervasi,16.666667
8186,8186,1500,3,2,True,False,110,flat,Eixample,13.636364
8187,8187,1500,3,2,True,False,110,flat,Eixample,13.636364

In [32]:
print(data['property_type'].unique())
print(data['property_type'].dtype)

['flat' 'attic' nan 'apartment' 'study']
object

In [33]:
data['property_type'].value_counts()

property_type
flat         6505
apartment     991
attic         315
study         109
Name: count, dtype: int64

In [29]:
data.rename(columns={'real_state': 'property_type'}, inplace=True)

In [34]:
data = data.dropna(subset=['property_type'])
data.reset_index(drop=True, inplace=True)

In [ ]:
data

In [35]:
!git add .

In [36]:
!git commit -m 'las filas con valor nulo en la columna real_state fueron eliminadas y cambio de nombre de esta columna a property_type'

On branch aran
nothing to commit, working tree clean

In [37]:
!git checkout main

Switched to branch 'main'
Your branch is up to date with 'origin/main'.

In [ ]:
!git pull origin main

In [ ]:
!git merge aran

In [ ]:
!git push https://Arantafall:@github.com/Arantafall/https://github.com/arantafall/housing_BCN.git/

In [ ]:
!git push https://Arantafall:@github.com/Arantafall/housing_BCN.git

In [ ]:
!pwd
%cd housing_BCN

In [ ]:
ls